# Generated by Django 6.0 on 2026-01-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.JSONField(default=dict),
        ),
    ]
